In [3]:
from decimal import *
import pandas as pd
import numpy as np
import math
x=10000*int(input('請輸入本金'))
y=int(input('請輸入期數'))
r=0.01*int(input('請輸入利息'))
a = math.ceil(x/12/y)
al = []
bl = []
cl = []
period=[]
i=1
while i < (y)*12+1:
        ai=min(a,x-a*(i-1))
        bi= (x-sum(al))*(r)*1/12
        bl.append( int((Decimal(bi).quantize(Decimal('1'), rounding=ROUND_HALF_UP))) )
        al.append( ai )
        ci= sum(al)+sum(bl)
        cl.append( ci )
        peri=str("第"+str(i)+"期")
        period.append( peri )
        i+=1

dic={ "本金":al, "利息":bl, "本金利息累計":cl}
df=pd.DataFrame(dic,index=period)
df

請輸入本金20
請輸入期數20
請輸入利息8

        本金    利息  本金利息累計
第1期    834  1333    2167
第2期    834  1328    4329
第3期    834  1322    6485
第4期    834  1317    8636
第5期    834  1311   10781
...    ...   ...     ...
第236期  834    27  357309
第237期  834    21  358164
第238期  834    16  359014
第239期  834    10  359858
第240期  674     4  360536

[240 rows x 3 columns]